apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "$CLOUDRUN_MIN_INSTANCES"
        autoscaling.knative.dev/maxScale: "$CLOUDRUN_MAX_INSTANCES"
        run.googleapis.com/gpu-zonal-redundancy-disabled: "true"
    spec:
      serviceAccountName: "$GCP_SERVICE_ACCOUNT_EMAIL"
      containers:
        image: "$DOCKER_IMAGE"
        ports:
          name: http1
          containerPort: 80
        env:
          - name: SAM2_HUGGING_FACE_MODEL_ID
            value: facebook/sam2-hiera-tiny
          - name: TORCH_DEVICE
            value: cpu
          - name: GCS_RAW_DOCUMENTS_BUCKET_NAME
            value: "$GCS_RAW_DOCUMENTS_BUCKET_NAME"
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
  traffic:
    - percent: 100
      latestRevision: true