on:
  workflow_call:

jobs:
  build:
    defaults:
      run:
        working-directory: application/ai
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - uses: actions/setup-python@v5
        with:
          python-version-file: "application/ai/pyproject.toml"

      - name: install system dependencies
        run: sudo apt install -y poppler-utils

      - run: pip install -r dev-requirements.txt

      - name: formatting checks
        run: isort --check geo_document_intelligence && black --check .

      - run: pylint . && lint-imports

      - run: pyright

      - run: pytest