on:
  workflow_call:
    inputs:
      gcp_service_account_email:
        type: string
        required: true
      gcp_workload_identity_provider_id:
        type: string
        required: true
      gcp_region:
        type: string
        required: true
      gcp_project:
        type: string
        required: true
jobs:
  build:
    defaults:
      run:
        working-directory: application/ai
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: impersonate gcp service account
        id: gcp_auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: access_token
          service_account: ${{inputs.gcp_service_account_email}}
          workload_identity_provider: ${{inputs.gcp_workload_identity_provider_id}}

      - name: login to gcp artifact registry
        uses: docker/login-action@v3
        with:
          registry: ${{inputs.gcp_region}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp_auth.outputs.access_token }}

      - uses: actions/setup-python@v5
        with:
          python-version-file: "application/ai/pyproject.toml"

      - name: install system dependencies
        run: sudo apt install -y poppler-utils

      - run: pip install -r dev-requirements.txt

      - name: formatting checks
        run: isort --check geo_document_intelligence && black --check .

      - run: pylint . && lint-imports

      - run: pyright

      - run: pytest

      - name: build and push docker image to gcp artifact registry
        uses: docker/build-push-action@v6
        with:
          context: application/ai
          push: true
          tags: ${{inputs.gcp_region}}-docker.pkg.dev/${{inputs.gcp_project}}/docker/ai:latest
