on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      gcp_service_account_email:
        type: string
        required: true
      gcp_workload_identity_provider_id:
        type: string
        required: true

jobs:
  deploy:
    defaults:
      run:
        working-directory: application/terraform/environments/${{inputs.environment}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{inputs.gcp_service_account_email}}
          workload_identity_provider: ${{inputs.gcp_workload_identity_provider_id}}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - run: echo 'ai_api_runner_service_account_id = "ai-api-runner"' > terraform.tfvars

      - run: terraform init

      - run: terraform plan -out=tfplan

      - run: terraform apply tfplan
