on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      gcp_service_account_email:
        type: string
        required: true
      gcp_workload_identity_provider_id:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "google-github-actions/auth@v2"
        with:
          service_account: ${{inputs.gcp_service_account_email}}
          workload_identity_provider: ${{inputs.gcp_workload_identity_provider_id}}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - run: terraform init
        working-directory: platform/terraform/environments/${{inputs.environment}}

      - run: terraform plan -out=tfplan
        working-directory: platform/terraform/environments/${{inputs.environment}}

      - run: terraform apply tfplan
        working-directory: platform/terraform/environments/${{inputs.environment}}