on:
    workflow_call:
      inputs:
        gcp_region:
          type: string
          required: true
        gcp_project_id:
          type: string
          required: true
        gcp_deployer_service_account_email:
          type: string
          required: true
        gcp_runner_service_account_email:
          type: string
          required: true
        gcp_workload_identity_provider_id:
          type: string
          required: true
        gcs_raw_documents_bucket_name:
          type: string
          required: true
        cloudrun_min_instances:
          type: number
          required: true
        cloudrun_max_instances:
          type: number
          required: true
        docker_image_digest:
          type: string
          required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:

      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{inputs.gcp_deployer_service_account_email}}
          workload_identity_provider: ${{inputs.gcp_workload_identity_provider_id}}

      - name: template cloudrun service description
        run: cat application/ai/api-template.service.yml | envsubst | tee ai-api.service.yml
        env:
          GCS_SERVICE_ACCOUNT_EMAIL: ${{inputs.gcp_runner_service_account_email}}
          GCS_RAW_DOCUMENTS_BUCKET_NAME: ${{inputs.gcs_raw_documents_bucket_name}}
          CLOUDRUN_MIN_INSTANCES:  ${{inputs.cloudrun_min_instances}}
          CLOUDRUN_MAX_INSTANCES:  ${{inputs.cloudrun_max_instances}}
          DOCKER_IMAGE: ${{inputs.gcp_region}}-docker.pkg.dev/${{inputs.gcp_project_id}}/docker/ai@${{inputs.docker_image_digest}}
      
      - name: deploy to cloudrun
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          metadata: ai-api.service.yml
          region: ${{inputs.gcp_region}}
          project_id: ${{inputs.gcp_project_id}}
