on:
  pull_request:
    paths:
      - application/hitl/**
jobs:
  build_pre_production_application_infrastructure:
    uses: ./.github/workflows/build-application-infrastructure.yml
    with:
      environment: pre-production
