on:
  push:
    paths:
      - application/ai/**
    branches:
      - main
jobs:

  build_pre_production_application_infrastructure:
    uses: ./.github/workflows/build-application-infrastructure.yml
    with:
      environment: pre-production

  build_pre_production_application:
    uses: ./.github/workflows/build-application-ai.yml

  deploy_pre_production_application_infrastructure:
    needs:
      - build_pre_production_application_infrastructure
      - build_pre_production_application
    uses: ./.github/workflows/deploy-application-infrastructure.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: pre-production
      gcp_service_account_email: app-deployer@geo-document-intelligence-pre.iam.gserviceaccount.com
      gcp_workload_identity_provider_id: projects/505462349330/locations/global/workloadIdentityPools/ci-cd/providers/ci-cd-github-actions

  deploy_pre_production_application:
    uses: ./.github/workflows/deploy-application-ai.yml
    needs:
      - build_pre_production_application
      - deploy_pre_production_application_infrastructure
    permissions:
      contents: "read"
      id-token: "write"
    with:
      gcp_region: europe-west4
      gcp_project_id: geo-document-intelligence-pre
      gcp_deployer_service_account_email: app-deployer@geo-document-intelligence-pre.iam.gserviceaccount.com
      gcp_runner_service_account_email: app-runner@geo-document-intelligence-pre.iam.gserviceaccount.com
      gcp_workload_identity_provider_id: projects/505462349330/locations/global/workloadIdentityPools/ci-cd/providers/ci-cd-github-actions
      gcs_raw_documents_bucket_name: geo-document-intelligence-pre
      cloudrun_min_instances: 0
      cloudrun_max_instances: 1