on:
  push:
    paths:
      - platform/**
    branches:
      - main
jobs:
  build_pre_production_platform_infrastructure:
    uses: ./.github/workflows/build-platform-infrastructure.yml
    with:
      environment: pre-production

  deploy_pre_production_platform_infrastructure:
    needs: build_pre_production_platform_infrastructure
    uses: ./.github/workflows/deploy-platform-infrastructure.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: pre-production
      gcp_service_account_email: platform-deployer@geo-document-intelligence-pre.iam.gserviceaccount.com
      gcp_workload_identity_provider_id: projects/505462349330/locations/global/workloadIdentityPools/ci-cd/providers/ci-cd-github-actions
    if: false
