on:
  pull_request:
    paths:
      - application/ai/**
jobs:

  build_pre_production_application_infrastructure:
    uses: ./.github/workflows/build-application-infrastructure.yml
    with:
      environment: pre-production

  build_pre_production_application_ai:
    uses: ./.github/workflows/build-application-ai.yml
