on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        working-directory: application/e2e-tests
        env:
          BASE_URL: ${{ github.event.client_payload.url }}